"""Reviewed wording for the desktop interface."""
EN={
'当前方案 · 游戏实测':'Current combination · Measured in game',
'已测试方案 · 游戏实测':'Tested combination · Measured in game',
'候选方案 · 预测颜色':'Candidate · Predicted colors',
'正在定位此方案':'Positioning this combination',
'实测达标':'Measured within target',
'教程':'How to use','使用教程':'How to use Color Studio',
'支持作者':'Support the creator','♥  支持作者':'♥  Support',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'Supporting the creator is entirely optional. All features are available whether or not you donate.',
'选择您偏好的平台支持后续开发，感谢您的支持。':'Select a platform to support future development. Thank you.',
'爱发电':'Afdian','关闭':'Close','提交问题 / Issues':'Report an issue',
'1. 设置游戏窗口':'1. Set the game resolution',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'In the game, open Graphics → Display settings → Windowed mode → Resolution, and choose 1280 × 960.',
'2. 选择游戏窗口':'2. Select the game window',
'在本工具左上角选择正在运行游戏的窗口；只有一个游戏窗口时也可以使用自动检测。':'Select the game window at the top left of this tool. Auto-detect also works when only one game window is open.',
'3. 设置目标颜色':'3. Choose the target colors',
'设置需要固定的颜色，并启用对应染色区域。可输入 HEX 色码、点击选色，或使用屏幕吸管。':'Set the target colors and enable their dye regions. Enter HEX codes, choose a color, or use the eyedropper.',
'4. 选择匹配模式':'4. Choose a matching mode',
'5. 启动后再进入染色':'5. Start the tool, then open dyeing',
'按 F8 或点击开始。待浮窗出现后，再手动打开游戏内染色倒计时界面；识别成功后程序自动开始。':'Press F8 or click Start. Once the overlay appears, manually open the timed dye screen in the game. The tool starts automatically after recognizing it.',
'6. 自动操作期间':'6. While the tool is running',
'请尽量不要操作鼠标，保持游戏在前台，不要移动或缩放游戏窗口。按 F9 可随时停止；是否使用染色结果，请在游戏内手动确认。':'Avoid moving the mouse. Keep the game in the foreground and leave its window position and size unchanged. Press F9 to stop at any time; application must be confirmed manually in the game.',
'关于等待与候选方案':'Timing and alternative combinations',
'Tips 1 · 匹配方式':'Tip 1 · Matching modes',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'Exact HEX requires an identical code. Similar uses the configured Delta E tolerance; try 10 to start.',
'为每个区域选择精准或相似模式。':'Choose Exact or Similar for each region.',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。方案综合考虑各区域色差和落点附近的颜色变化，优先选择稳定、均衡的结果；整体质量相同时优先精准命中。':'Exact mode requires identical HEX codes; Similar mode uses the configured tolerance. Combinations are compared by color differences across all regions and nearby color variation, favoring stable, balanced results. Exact hits take priority when overall quality is equal.',
'本轮可执行方案均有区域偏离目标色系，以下按综合色差与落点稳定性排序。':'Every available executable combination has at least one region outside its target color family. Combinations are ranked by overall color difference and landing stability.',
'存在色系偏离':'Color family mismatch',
'部分区域与目标色系不符。':'Some regions do not match their target color families.',
'Tips 2 · 等待与候选':'Tip 2 · Waiting and alternatives',
'单区域会跳过整板拼接，使用平移和少量缩放直接寻色。精准模式从识别画板起约 60 秒内优先寻找精确 HEX，未命中时尝试定位本轮最佳实测妥协结果；收尾可能略多几秒。精准或相似目标连续两帧达标后立即停下，剩余时间可手动调整。多区域先拼图再寻色，浮窗会显示进度及候选方案。':'Single-region search skips full-board stitching and explores with translation and limited zoom. Exact mode prioritizes an identical HEX for about 60 seconds after board detection, then attempts to position the best measured compromise if no exact match is found; finalization may take a few extra seconds. The tool stops as soon as two consecutive readings meet the Exact or Similar target, leaving time for manual adjustment. With multiple regions enabled, it stitches the board before searching; the overlay shows progress and candidate combinations.',
'结果与问题反馈':'Results and feedback',
'自动染色并非完美，最终色差可能较大。如结果未达到预期，可重新开始一局。遇到问题请到 GitHub 提交 Issue，并附上本次日志。':'Automatic dyeing is not perfect, and the final color difference may be large. If the result is unsatisfactory, the round may be repeated. Report problems on GitHub with the session log.',
'就绪 · 请先选择游戏窗口和目标颜色':'Ready · Select the game window and target colors',
'拖动标题可移动浮窗':'Drag this header to move','不透明度':'Opacity','收起':'Collapse','展开':'Expand','停止 F9':'Stop F9',
'等待手动进入染色倒计时；F9 可停止。':'Open the timed dye screen manually. F9 stops.',
'识别与缩放':'Detecting and zooming','采集颜色板':'Capturing the board','对齐采集画面':'Aligning captured frames',
'测量色板周期':'Measuring board repetition','拼接全局颜色板':'Building the full board','保存颜色板':'Saving the board',
'检查拼图质量':'Checking board quality','搜索目标颜色':'Searching for target colors','计算旋转与缩放':'Calculating rotation and zoom',
'准备候选方案':'Preparing combinations','移动到目标位置':'Moving to the target','复核游戏色码':'Verifying game colors',
'正在按目标计算，请稍候。':'Calculating the color combinations. Please wait.',
'步骤 ':'Step ','已用 ':'Elapsed ',' 秒':' s','游戏剩余 ':'Game time left: ','本阶段 ':'This stage: ',
'区域 ':'Region ','预测 ':'Predicted ','实测 ':'Measured ','最大实测色差':'Maximum measured difference',
'自动方案实测色码':'Automatic result · game HEX',
'已停止，请查看游戏当前颜色。':'Stopped. Review the current colors in the game.',
'正在采集本局颜色板。':'Capturing this round’s color board.',
'等待用户手动进入倒计时染色界面':'Waiting for the timed dye screen to be opened.',
'候选选择已结束。':'Combination selection has ended.',
'全部目标达标，请在游戏内手动确认是否套用。':'All targets met. Confirm the final dye in the game.',
'正在定位所选方案':'Positioning the selected combination',
'根据图像实测位移校正；F9随时停止。':'Correcting the position using measured movement. F9 stops.',
'游戏色码已复核':'Game colors verified',
'图像处理中，鼠标暂时不动是正常现象。':'Images are being processed. The mouse stays still during this stage.',
'当前结果已达到所设目标，请在游戏内手动确认。':'The current result meets the configured targets. Confirm application manually in the game.',
'当前结果未达到全部目标；请先查看妥协方案，再在游戏内手动确认是否套用。':'Not all targets were met. Review the compromise result before deciding.',
'未找到满足所设目标的组合，正在定位最接近的妥协方案。':'No combination met the configured criteria. Positioning the closest compromise.',
'未精准匹配 · 妥协方案':'Not an exact match · Compromise',
'未命中目标 · 妥协方案':'Target not reached · Compromise',
'未找到满足目标的颜色；下方显示本轮已实测确认的妥协结果。这是寻色未命中后的正常结束状态，并非程序故障。请查看色差，并在游戏内手动确认是否采用。':'No color met the configured target. The result below is a measured compromise from this search. This is the normal outcome when no match is found, not a tool failure. Review the color difference and decide in the game whether to apply it.',
'未找到满足目标的颜色。此前最佳实测结果未能恢复；下方显示当前已复核的妥协结果，请以游戏内当前颜色为准。':'No color met the configured target. The previously measured best could not be restored; the compromise below shows the current verified result. Refer to the colors currently shown in the game.',
'妥协方案（未达目标） · 本次结果':'Compromise (target not reached) · Final result',
' · 最大色差 ΔE ':' · Maximum difference ΔE ',
' · 色差越小越接近目标':' · Lower is closer to the target',
'精准匹配':'Exact match',
'本轮搜索没有可测量的落点；无法生成自动或妥协方案。':'No measurable position was found. No automatic or compromise combination is available.',
'六位色码必须完全一致':'The six-digit HEX code must match exactly',
'目标色差 ΔE ≤ ':'Target color difference ΔE ≤ ',
' · 数值越小越接近目标':' · Lower values are closer to the target',
'正在采集本局颜色板':'Capturing this round’s color board',
'精准命中 ':'Exact HEX hits ',
'未找到游戏窗口。请启动游戏，或手动选择窗口。':'Game window not found. Start the game, or select its window manually.',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'The countdown could not be read reliably. No zoom or scan was started, but this dye was consumed. Check OCR before trying again.',
'正在复核倒计时识别':'Rechecking the countdown reading',
'正在寻色 · 游戏剩余 ':'Searching · game time left: ',
'正在恢复最佳颜色 · 游戏剩余 ':'Restoring the best colors · game time left: ',
'当前颜色  ':'Current color  ','最佳结果  ':'Best result  ',
'本次结果':'Current result','最佳组合':'Best combination',
'最大色差 ΔE ':'Maximum difference ΔE ',' / 平均 ':' / mean ',
' · 色差越小越接近目标':' · lower is closer to the target',
' 秒':' s',
}
TW={
'当前方案 · 游戏实测':'目前方案 · 遊戲實測',
'已测试方案 · 游戏实测':'已測試方案 · 遊戲實測',
'候选方案 · 预测颜色':'候選方案 · 預測顏色',
'正在定位此方案':'正在定位此方案',
'实测达标':'實測達標',
'等待用户手动进入倒计时染色界面':'等待您手動進入限時染色畫面。',
'Tips 1 · 匹配方式':'提示 1・比對模式','Tips 2 · 等待与候选':'提示 2・等待與候選',
'单区域会跳过整板拼接，使用平移和少量缩放直接寻色。精准模式从识别画板起约 60 秒内优先寻找精确 HEX，未命中时尝试定位本轮最佳实测妥协结果；收尾可能略多几秒。精准或相似目标连续两帧达标后立即停下，剩余时间可手动调整。多区域先拼图再寻色，浮窗会显示进度及候选方案。':'單區域會略過整板拼接，使用平移與少量縮放直接尋色。精準模式從辨識色板起約 60 秒內優先尋找精確 HEX，未命中時嘗試定位本局最佳實測折衷結果；收尾可能稍多幾秒。精準或相似目標連續兩幀達標後立即停止，剩餘時間可手動調整。多區域先拼圖再尋色，浮窗會顯示進度與候選方案。',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'精準 HEX 必須完全一致；相似模式依設定的 ΔE 容差搜尋，建議先從 10 開始。',
'为每个区域选择精准或相似模式。':'為每個區域選擇精準或相似模式。',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。方案综合考虑各区域色差和落点附近的颜色变化，优先选择稳定、均衡的结果；整体质量相同时优先精准命中。':'精準模式要求 HEX 完全一致；相似模式使用設定的色差範圍。方案綜合考量各區域色差與落點附近的顏色變化，優先選擇穩定、均衡的結果；整體品質相同時優先精準命中。',
'本轮可执行方案均有区域偏离目标色系，以下按综合色差与落点稳定性排序。':'本輪可執行方案皆有區域偏離目標色系，以下依綜合色差與落點穩定性排序。',
'存在色系偏离':'色系偏離',
'部分区域与目标色系不符。':'部分區域與目標色系不符。',
'六位色码必须完全一致':'六位色碼必須完全一致',
'目标色差 ΔE ≤ ':'目標色差 ΔE ≤ ',
' · 数值越小越接近目标':' · 數值越小越接近目標',
'正在采集本局颜色板':'正在採集本局顏色板',
'精准命中 ':'精準命中 ',
'未命中目标 · 妥协方案':'未命中目標・折衷方案',
'未找到满足目标的颜色；下方显示本轮已实测确认的妥协结果。这是寻色未命中后的正常结束状态，并非程序故障。请查看色差，并在游戏内手动确认是否采用。':'未找到符合目標的顏色；下方顯示本局已實測確認的折衷結果。這是未命中目標時的正常結束狀態，並非工具故障。請查看色差，並在遊戲內手動確認是否採用。',
'未找到满足目标的颜色。此前最佳实测结果未能恢复；下方显示当前已复核的妥协结果，请以游戏内当前颜色为准。':'未找到符合目標的顏色。先前最佳實測結果未能恢復；下方顯示目前已複核的折衷結果，請以遊戲內目前顏色為準。',
'妥协方案（未达目标） · 本次结果':'折衷方案（未達目標）・本次結果',
' · 最大色差 ΔE ':'・最大色差 ΔE ',
' · 色差越小越接近目标':'・色差越小越接近目標',
'教程':'使用教學','使用教程':'使用教學',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'贊助完全自願，無論是否贊助，都能正常使用本工具的所有功能。',
'选择您偏好的平台支持后续开发，感谢您的支持。':'如需支持後續開發，請選擇適合的平台。感謝您的支持。',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'在遊戲中依序開啟【圖形】→【畫面設定】→【視窗模式】→【解析度】，設為 1280 × 960。',
'提交问题 / Issues':'回報問題 / Issues',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'倒數計時無法可靠辨識，未開始縮放或掃描；本次染劑已消耗，請先檢查 OCR 再重新執行。',
}

# Current product copy. Historical keys above only translate archived events.
EN.update({
'准备寻色':'Preparing search',
'正在准备寻色，暂时不要进入染色界面；等提示就绪后再开始。F9 可停止。':'Preparing search. Wait for the ready message before opening dyeing. F9 stops.',
'寻色准备未完成':'Search preparation incomplete',
'本次准备未能完成，已停止并保存诊断记录。请在游戏普通界面重试，无需消耗染色道具。':'Preparation could not finish. The tool stopped and saved diagnostics. Retry on an ordinary game screen; no dye item is needed.',
'完整切换与返回路线超过剩余操作额度，已保留当前实测结果。':'The full switch and return exceed the remaining action allowance. The current measured result has been kept.',
'当前色板位置或颜色已变化，已重新读取；请选择当前候选。':'The palette position or colors changed and were read again. Select from the current candidates.',
'所选候选已失效，已保留当前颜色。':'The selected candidate has expired. Current colors have been kept.',
'所选方案暂时无法安全切换，已保留当前实测结果。':'The selected combination cannot be switched to safely at present. The current measured result has been kept.',
'已保留您选择的方案。请查看各区域实测色差，在游戏内手动确认是否套用。':'Your selected combination has been kept. Review each region’s measured color difference and confirm application manually in the game.',
'所选方案返回未完成复核':'Selected combination return unverified',
'切换后的恢复结果尚未确认。请以游戏当前颜色为准，详细记录已保存。':'Recovery after switching is unconfirmed. Refer to the current colors in the game. Detailed records were saved.',
'精准寻色读取本局色板，规划平移、缩放与旋转，并核对游戏色码。找到目标后仍提供按优先级与色差排序的其他候选；时间允许时自动定位。切换前核对完整路线与返回余量，时间不足时保留当前颜色。预测颜色不等于实测达标。':'Precise Search reads this round’s palette, plans translation, zoom and rotation, and checks game HEX values. Other candidates remain available after a target is found, ordered by region priority order and color difference. The tool positions the target when time permits. Switching requires a full route and return allowance; current colors are kept if time is insufficient. Predicted colors do not prove a measured match.',
'本轮候选方案':'This round’s alternatives',
'候选按区域优先级与色差排序':'Alternatives ordered by region priority and color difference',
'可选择其他方案，切换前会核对剩余时间和返回路线。实际染色请在游戏内手动确认。':'Choose another combination if desired. Remaining time and a return route are checked before switching. Confirm application manually in the game.',
'候选选择已结束，以下方案仅供查看。':'Selection has ended. The combinations below are for reference only.',
'当前方案':'Current combination',
'当前方案（实测）':'Current combination (measured)',
'尚未执行':'Not executed',
'当前颜色已复核，可选择其他方案。':'Current colors are verified. You may choose another combination.',
'所选方案已复核':'Selected combination verified',
'已保留当前方案':'Current combination kept',
'查看本轮候选':'View this round’s alternatives',
'关闭候选':'Close alternatives',
'扫描色板实例':'Scanning palette instances',
'正在准备只读扫描，暂时不要进入染色界面；等提示就绪后再开始。F9 可停止。':'Preparing the read-only scan. Wait for the ready message before opening dyeing. F9 stops.',
'正在等待并检查活动染色板；F9 可停止。':'Waiting for and checking an active dye board. F9 stops.',
'游戏初始化检查超时':'Game initialization check timed out',
'进程或窗口检查尚未完成。请在游戏普通界面重试，并附上本次诊断记录。':'Process or window checks are incomplete. Retry on an ordinary game screen and include this diagnostic record.',
'色板扫描尚未完成':'Palette scan incomplete',
'本次扫描未能完成候选和唯一性检查，不能据此判断没有染色板。请在游戏普通界面重新准备，等提示就绪后再进入染色。':'Candidate and uniqueness checks did not finish. This does not establish that no board exists. Prepare again on an ordinary game screen and wait for the ready message before opening dyeing.',
'未能唯一绑定染色板':'Could not bind a unique dye board',
'检测到多个活动色板候选。请确认只打开了一个染色板，并附上诊断记录。':'Multiple active board candidates were detected. Check that only one dye board is open and include the diagnostic record.',
'等待染色界面超时':'Waiting for dyeing timed out',
'等待期间未找到已验证的活动染色板，本轮没有发送操作。':'No validated active board was found while waiting. No input was sent this round.',
'无法读取游戏进程（权限被拒绝）':'Cannot read the game process (access denied)',
'请让工具与游戏使用相同权限级别；若游戏以管理员运行，请右键工具选择「以管理员身份运行」后重开。先在游戏普通界面重试，确认权限检查通过后再开始新一局染色。':'Run the tool and game at the same privilege level. If the game runs as administrator, right-click the tool and choose Run as administrator. Retry on an ordinary game screen first; start a dye round only after the access check passes.',
'启用需要染色的区域，输入 HEX 色码、点击选色或使用屏幕吸管。替代颜色同样视为可接受的目标。工具自动识别双区域或三区域色板；本局不存在的区域不参与匹配，保存的设置仍会保留。':'Enable the regions to match. Enter HEX codes, choose colors, or use the eyedropper. Alternatives are also accepted targets. The tool detects two- or three-region boards automatically; absent regions are excluded without changing saved settings.',
'本局不可用':'Unavailable this round',
'当前颜色  本局不可用':'Current color · Unavailable this round',
'最佳结果  本局不可用':'Best result · Unavailable this round',
'已识别双区域色板':'Two-region dye board detected',
'已识别 2 个染色区域，区域 3 本局不可用。':'Detected 2 dye regions. Region 3 is unavailable this round.',
'本局没有已启用的可用区域':'No available regions are enabled',
'本局没有已启用的可用区域，请启用区域 1 或 2。':'No available regions are enabled. Enable Region 1 or 2.',
'目标色集合 · 1 色 · 点击查看全部':'Allowed colors · 1 color · View all colors',
'F9 随时停止并释放鼠标  ·  切换窗口停止寻色  ·  不自动开启下一瓶染色剂':'F9 stops and releases the mouse · Switching windows stops search · No automatic next dye',
'剩余操作额度不足，已保留当前颜色':'Insufficient remaining actions; current colors kept',
'完整路线超过本轮剩余操作额度，未执行部分路线；请查看当前游戏颜色。':'The full route exceeds the remaining action allowance. No partial route was executed; review the current game colors.',
'当前设置无法读取，原文件已保留。':'Current settings could not be read. The original file was kept.',
'颜色复核暂未完成，已停止':'Color verification incomplete; stopped',
'已保留能够读取的游戏色码；该记录未完成截图复核，请以游戏当前颜色为准。':'Available game HEX values were retained. Screenshot verification is incomplete; refer to the current colors in the game.',
'1. 选择游戏窗口':'1. Select the game window',
'在左上角选择游戏窗口；只有一个游戏窗口时可自动检测。无需设置固定分辨率。':'Select the game window at the top left. A single game window can be detected automatically. No fixed resolution is required.',
'2. 设置目标颜色':'2. Set target colors',
'启用需要染色的区域，输入 HEX 色码、点击选色或使用屏幕吸管。替代颜色同样视为可接受的目标。':'Enable the regions to match. Enter HEX codes, choose colors, or use the eyedropper. Alternative colors are also accepted targets.',
'3. 选择匹配模式':'3. Choose matching modes',
'精准 HEX 要求六位色码完全一致；相似颜色按各区域设置的 ΔE 色差范围匹配。':'Exact HEX requires the identical six-digit code. Similar uses each region’s configured ΔE tolerance.',
'4. 设置区域优先级':'4. Set region priorities',
'1 为最高优先级。程序先寻找全部启用区域达标的组合；未找到时，依次优先满足高优先级区域，再降低色差。调整一个区域会自动交换另一区域的优先级。':'Priority 1 is highest. The tool first seeks a combination meeting every enabled target. Otherwise, it favors targets in priority order, then reduces color differences. Changing a priority swaps it with the other region.',
'5. 开始寻色':'5. Start searching',
'按 F8 或点击开始，等待提示后手动进入游戏染色界面。也可在已经进入染色界面后启动工具。使用默认的精准寻色；图像寻色仅在精准寻色故障时使用。':'Press F8 or click Start, then open the dye screen after the waiting message. You can also start after opening the dye screen. Use Precise Search by default; Visual Search is a fallback if Precise Search fails.',
'请尽量不要操作鼠标，保持游戏在前台，不要移动或缩放游戏窗口。按 F9 可随时停止；是否使用染色结果，请在游戏内手动确认。':'Keep the game in front and avoid moving the mouse or resizing its window. F9 stops at any time. Confirm any dye result manually in the game.',
'保持游戏在前台，尽量不要操作鼠标，也不要移动或调整游戏窗口。按 F9 可随时停止。程序不会自动开启染色、套用或确认结果，请在游戏内自行决定。':'Keep the game in front. Avoid using the mouse, moving or resizing the game window. F9 stops at any time. The tool does not start a dye round or apply or confirm its result; decide manually in the game.',
'Tips 1 · 寻色与结果':'Tip 1 · Search and results',
'精准寻色读取本局色板，联合规划平移、缩放与旋转，并回读游戏色码。全部目标达标后停止；未全部达标时尽量保留按优先级排序的最佳实测妥协结果。预测颜色不等于实际达标。':'Precise Search reads this round’s palette, plans translation, zoom and rotation together, and checks game HEX values. It stops when all targets are met, or tries to retain the best measured compromise in priority order. Predicted colors do not prove a match.',
'Tips 2 · 材质限制':'Tip 2 · Material limits',
'游戏内皮革、木材等材质的基础色不含纯黑或纯白时，无法精准抓取 #000000 或 #FFFFFF。请以游戏实际显示的色码为准。':'When the base palette of leather, wood or another material lacks pure black or white, #000000 or #FFFFFF cannot be matched exactly. Refer to the HEX values shown in the game.',
'Tips 3 · 多色精准':'Tip 3 · Multiple exact colors',
'多个区域共享色板的平移、缩放与旋转，目标组合不一定同时可达。多色精准抓取不能保证成功率；请检查妥协结果的各区域色差后再决定是否使用。':'Regions share palette translation, zoom and rotation, so their targets may not be reachable together. Multiple exact matches are not guaranteed. Review each region’s compromise color difference before applying it.',
'Tips 4 · 自动保存与方案':'Tip 4 · Autosave and presets',
'颜色、区域开关、匹配模式和优先级会自动保存，下次启动恢复。点击保存方案可命名保存多套配置，也可编辑、载入或删除方案。':'Colors, region switches, matching modes and priorities are saved automatically and restored next time. Save preset lets you name, edit, load and delete multiple configurations.',
'最终结果以游戏当前色码为准。遇到问题请在 GitHub 提交 Issue，并附上本次日志；不要为了反馈反复消耗染色道具。':'Use the game’s current HEX values as the final result. Report problems on GitHub with the session log; additional dye items are not needed just to report a problem.',
'图像寻色：精准寻色故障时使用。':'Visual Search: use if Precise Search fails.',
'优先级':'Priority',
'染色方案':'Dye presets',
'当前设置自动保存。这里可命名保存多套方案，也可单独编辑方案。':'Current settings save automatically. Name multiple presets here, or edit a preset independently.',
'新方案':'New preset','方案名称':'Preset name','保存新方案':'Save new preset','保存修改':'Save changes',
'载入到主界面':'Load into main window','用当前设置新建':'New from current settings','删除方案':'Delete preset',
'替代颜色':'Alternative colors','1 为最高优先级；全部区域达标始终优先。':'1 is highest; meeting all enabled targets always comes first.',
'方案已保存。':'Preset saved.','方案已载入，当前设置已自动保存。':'Preset loaded. Current settings were saved automatically.',
'确定删除所选方案？':'Delete the selected preset?',
'设置未能自动保存，请检查数据目录是否可写。':'Settings could not be saved automatically. Check that the data folder is writable.',
'请先停止寻色，再载入方案。':'Stop searching before loading a preset.',
'方案格式无效。':'Invalid preset format.','方案必须包含三个区域。':'A preset must contain three regions.',
'区域优先级必须包含三个不同区域。':'Priorities must contain three distinct regions.',
'寻色方式无效。':'Invalid search strategy.','区域设置无效。':'Invalid region settings.','颜色输入无效。':'Invalid color input.',
'匹配模式或色差范围无效。':'Invalid matching mode or tolerance.','替代颜色最多为 63 个。':'Up to 63 alternative colors are supported.',
'请至少启用一个区域。':'Enable at least one region.','方案库格式无效。':'Invalid preset library format.',
'方案库包含重复记录。':'The preset library contains duplicate records.',
'方案库无法读取，请保留文件并检查内容。':'The preset library could not be read. Keep the file and inspect its contents.',
'所选方案已不存在。':'The selected preset no longer exists.',
'方案名称请输入 1 至 60 个字符。':'Enter a preset name of 1 to 60 characters.',
'此方案名称已存在，请使用其他名称。':'That preset name already exists. Choose a different name.',
})
TW.update({
'准备寻色':'準備尋色',
'正在准备寻色，暂时不要进入染色界面；等提示就绪后再开始。F9 可停止。':'正在準備尋色，暫時不要進入染色畫面；等提示就緒後再開始。F9 可停止。',
'寻色准备未完成':'尋色準備尚未完成',
'本次准备未能完成，已停止并保存诊断记录。请在游戏普通界面重试，无需消耗染色道具。':'本次準備未能完成，已停止並儲存診斷紀錄。請在遊戲普通畫面重試，無需消耗染色道具。',
'完整切换与返回路线超过剩余操作额度，已保留当前实测结果。':'完整切換與返回路線超過剩餘操作額度，已保留目前實測結果。',
'当前色板位置或颜色已变化，已重新读取；请选择当前候选。':'目前色板位置或顏色已變化，已重新讀取；請選擇目前候選。',
'所选候选已失效，已保留当前颜色。':'所選候選已失效，已保留目前顏色。',
'所选方案暂时无法安全切换，已保留当前实测结果。':'所選方案暫時無法安全切換，已保留目前實測結果。',
'已保留您选择的方案。请查看各区域实测色差，在游戏内手动确认是否套用。':'已保留您選擇的方案。請查看各區域實測色差，在遊戲內手動確認是否套用。',
'所选方案返回未完成复核':'所選方案返回尚未完成複核',
'切换后的恢复结果尚未确认。请以游戏当前颜色为准，详细记录已保存。':'切換後的恢復結果尚未確認。請以遊戲目前顏色為準，詳細紀錄已儲存。',
'精准寻色读取本局色板，规划平移、缩放与旋转，并核对游戏色码。找到目标后仍提供按优先级与色差排序的其他候选；时间允许时自动定位。切换前核对完整路线与返回余量，时间不足时保留当前颜色。预测颜色不等于实测达标。':'精準尋色讀取本局色板，規劃平移、縮放與旋轉，並核對遊戲色碼。找到目標後仍提供依優先順序與色差排序的其他候選；時間允許時自動定位。切換前核對完整路線與返回餘量，時間不足時保留目前顏色。預測顏色不等於實測達標。',
'本轮候选方案':'本局候選方案',
'候选按区域优先级与色差排序':'候選依區域優先順序與色差排序',
'可选择其他方案，切换前会核对剩余时间和返回路线。实际染色请在游戏内手动确认。':'可選擇其他方案，切換前會核對剩餘時間與返回路線。實際染色請在遊戲內手動確認。',
'候选选择已结束，以下方案仅供查看。':'候選選擇已結束，以下方案僅供查看。',
'当前方案':'目前方案',
'当前方案（实测）':'目前方案（實測）',
'尚未执行':'尚未執行',
'当前颜色已复核，可选择其他方案。':'目前顏色已複核，可選擇其他方案。',
'所选方案已复核':'所選方案已複核',
'已保留当前方案':'已保留目前方案',
'查看本轮候选':'查看本局候選',
'关闭候选':'關閉候選',
'扫描色板实例':'掃描色板實例',
'正在准备只读扫描，暂时不要进入染色界面；等提示就绪后再开始。F9 可停止。':'正在準備唯讀掃描，暫時不要進入染色畫面；等提示就緒後再開始。F9 可停止。',
'正在等待并检查活动染色板；F9 可停止。':'正在等待並檢查活動染色色板；F9 可停止。',
'游戏初始化检查超时':'遊戲初始化檢查逾時',
'进程或窗口检查尚未完成。请在游戏普通界面重试，并附上本次诊断记录。':'程序或視窗檢查尚未完成。請在遊戲普通畫面重試，並附上本次診斷紀錄。',
'色板扫描尚未完成':'色板掃描尚未完成',
'本次扫描未能完成候选和唯一性检查，不能据此判断没有染色板。请在游戏普通界面重新准备，等提示就绪后再进入染色。':'本次掃描未能完成候選與唯一性檢查，無法據此判斷沒有染色色板。請在遊戲普通畫面重新準備，等提示就緒後再進入染色。',
'未能唯一绑定染色板':'未能唯一綁定染色色板',
'检测到多个活动色板候选。请确认只打开了一个染色板，并附上诊断记录。':'偵測到多個活動色板候選。請確認只開啟了一個染色色板，並附上診斷紀錄。',
'等待染色界面超时':'等待染色畫面逾時',
'等待期间未找到已验证的活动染色板，本轮没有发送操作。':'等待期間未找到已驗證的活動染色色板，本局沒有傳送操作。',
'无法读取游戏进程（权限被拒绝）':'無法讀取遊戲程序（權限被拒絕）',
'请让工具与游戏使用相同权限级别；若游戏以管理员运行，请右键工具选择「以管理员身份运行」后重开。先在游戏普通界面重试，确认权限检查通过后再开始新一局染色。':'請讓工具與遊戲使用相同權限層級；若遊戲以管理員執行，請右鍵工具選擇「以系統管理員身分執行」後重開。先在遊戲普通畫面重試，確認權限檢查通過後再開始新一局染色。',
'启用需要染色的区域，输入 HEX 色码、点击选色或使用屏幕吸管。替代颜色同样视为可接受的目标。工具自动识别双区域或三区域色板；本局不存在的区域不参与匹配，保存的设置仍会保留。':'啟用需要染色的區域，輸入 HEX 色碼、點擊選色或使用螢幕吸管。替代顏色同樣視為可接受的目標。工具自動辨識雙區域或三區域色板；本局不存在的區域不參與比對，已儲存的設定仍會保留。',
'本局不可用':'本局無法使用',
'当前颜色  本局不可用':'目前顏色 · 本局無法使用',
'最佳结果  本局不可用':'最佳結果 · 本局無法使用',
'已识别双区域色板':'已辨識雙區域色板',
'已识别 2 个染色区域，区域 3 本局不可用。':'已辨識 2 個染色區域，區域 3 本局無法使用。',
'本局没有已启用的可用区域':'本局沒有已啟用的可用區域',
'本局没有已启用的可用区域，请启用区域 1 或 2。':'本局沒有已啟用的可用區域，請啟用區域 1 或 2。',
'目标色集合 · 1 色 · 点击查看全部':'目標色集合 · 1 色 · 點擊查看全部',
'F9 随时停止并释放鼠标  ·  切换窗口停止寻色  ·  不自动开启下一瓶染色剂':'F9 隨時停止並釋放滑鼠 · 切換視窗停止尋色 · 不自動開啟下一瓶染劑',
'剩余操作额度不足，已保留当前颜色':'剩餘操作額度不足，已保留目前顏色',
'完整路线超过本轮剩余操作额度，未执行部分路线；请查看当前游戏颜色。':'完整路線超過本局剩餘操作額度，未執行部分路線；請查看目前遊戲顏色。',
'当前设置无法读取，原文件已保留。':'無法讀取目前設定，原檔案已保留。',
'颜色复核暂未完成，已停止':'顏色複核尚未完成，已停止',
'已保留能够读取的游戏色码；该记录未完成截图复核，请以游戏当前颜色为准。':'已保留能夠讀取的遊戲色碼；該紀錄尚未完成截圖複核，請以遊戲目前顏色為準。',
'1. 选择游戏窗口':'1. 選擇遊戲視窗',
'在左上角选择游戏窗口；只有一个游戏窗口时可自动检测。无需设置固定分辨率。':'在左上角選擇遊戲視窗；只有一個遊戲視窗時可自動偵測。無需設定固定解析度。',
'2. 设置目标颜色':'2. 設定目標顏色',
'启用需要染色的区域，输入 HEX 色码、点击选色或使用屏幕吸管。替代颜色同样视为可接受的目标。':'啟用需要染色的區域，輸入 HEX 色碼、點擊選色或使用螢幕吸管。替代顏色同樣視為可接受的目標。',
'3. 选择匹配模式':'3. 選擇比對模式',
'精准 HEX 要求六位色码完全一致；相似颜色按各区域设置的 ΔE 色差范围匹配。':'精準 HEX 要求六位色碼完全一致；相似顏色依各區域設定的 ΔE 色差範圍比對。',
'4. 设置区域优先级':'4. 設定區域優先順序',
'1 为最高优先级。程序先寻找全部启用区域达标的组合；未找到时，依次优先满足高优先级区域，再降低色差。调整一个区域会自动交换另一区域的优先级。':'1 為最高優先順序。程式先尋找全部啟用區域達標的組合；未找到時，依序優先滿足高優先區域，再降低色差。調整一個區域會自動交換另一區域的優先順序。',
'5. 开始寻色':'5. 開始尋色',
'按 F8 或点击开始，等待提示后手动进入游戏染色界面。也可在已经进入染色界面后启动工具。使用默认的精准寻色；图像寻色仅在精准寻色故障时使用。':'按 F8 或點擊開始，等待提示後手動進入遊戲染色畫面。也可在已進入染色畫面後啟動工具。預設使用精準尋色；圖像尋色僅在精準尋色故障時使用。',
'保持游戏在前台，尽量不要操作鼠标，也不要移动或调整游戏窗口。按 F9 可随时停止。程序不会自动开启染色、套用或确认结果，请在游戏内自行决定。':'保持遊戲在前景，盡量不要操作滑鼠，也不要移動或調整遊戲視窗。按 F9 可隨時停止。程式不會自動開啟染色、套用或確認結果，請在遊戲內自行決定。',
'Tips 1 · 寻色与结果':'提示 1・尋色與結果',
'精准寻色读取本局色板，联合规划平移、缩放与旋转，并回读游戏色码。全部目标达标后停止；未全部达标时尽量保留按优先级排序的最佳实测妥协结果。预测颜色不等于实际达标。':'精準尋色讀取本局色板，聯合規劃平移、縮放與旋轉，並回讀遊戲色碼。全部目標達標後停止；未全部達標時盡量保留依優先順序排序的最佳實測折衷結果。預測顏色不等於實際達標。',
'Tips 2 · 材质限制':'提示 2・材質限制',
'游戏内皮革、木材等材质的基础色不含纯黑或纯白时，无法精准抓取 #000000 或 #FFFFFF。请以游戏实际显示的色码为准。':'遊戲內皮革、木材等材質的基礎色不含純黑或純白時，無法精準抓取 #000000 或 #FFFFFF。請以遊戲實際顯示的色碼為準。',
'Tips 3 · 多色精准':'提示 3・多色精準',
'多个区域共享色板的平移、缩放与旋转，目标组合不一定同时可达。多色精准抓取不能保证成功率；请检查妥协结果的各区域色差后再决定是否使用。':'多個區域共享色板的平移、縮放與旋轉，目標組合不一定同時可達。多色精準抓取無法保證成功率；請檢查折衷結果的各區域色差後再決定是否使用。',
'Tips 4 · 自动保存与方案':'提示 4・自動儲存與方案',
'颜色、区域开关、匹配模式和优先级会自动保存，下次启动恢复。点击保存方案可命名保存多套配置，也可编辑、载入或删除方案。':'顏色、區域開關、比對模式與優先順序會自動儲存，下次啟動時恢復。點擊儲存方案可命名儲存多套設定，也可編輯、載入或刪除方案。',
'最终结果以游戏当前色码为准。遇到问题请在 GitHub 提交 Issue，并附上本次日志；不要为了反馈反复消耗染色道具。':'最終結果以遊戲目前色碼為準。遇到問題請在 GitHub 提交 Issue，並附上本次紀錄；不需為了回報反覆消耗染色道具。',
'图像寻色：精准寻色故障时使用。':'圖像尋色：精準尋色故障時使用。',
'优先级':'優先順序','染色方案':'染色方案',
'当前设置自动保存。这里可命名保存多套方案，也可单独编辑方案。':'目前設定會自動儲存。這裡可命名儲存多套方案，也可單獨編輯方案。',
'新方案':'新方案','方案名称':'方案名稱','保存新方案':'儲存新方案','保存修改':'儲存修改',
'载入到主界面':'載入主畫面','用当前设置新建':'以目前設定新增','删除方案':'刪除方案','替代颜色':'替代顏色',
'1 为最高优先级；全部区域达标始终优先。':'1 為最高優先順序；全部區域達標始終優先。',
'方案已保存。':'方案已儲存。','方案已载入，当前设置已自动保存。':'方案已載入，目前設定已自動儲存。',
'确定删除所选方案？':'確定刪除所選方案？',
'设置未能自动保存，请检查数据目录是否可写。':'設定無法自動儲存，請檢查資料目錄是否可寫入。',
'请先停止寻色，再载入方案。':'請先停止尋色，再載入方案。',
'方案格式无效。':'方案格式無效。','方案必须包含三个区域。':'方案必須包含三個區域。',
'区域优先级必须包含三个不同区域。':'區域優先順序必須包含三個不同區域。',
'寻色方式无效。':'尋色方式無效。','区域设置无效。':'區域設定無效。','颜色输入无效。':'顏色輸入無效。',
'匹配模式或色差范围无效。':'比對模式或色差範圍無效。','替代颜色最多为 63 个。':'替代顏色最多為 63 個。',
'请至少启用一个区域。':'請至少啟用一個區域。','方案库格式无效。':'方案庫格式無效。',
'方案库包含重复记录。':'方案庫包含重複紀錄。',
'方案库无法读取，请保留文件并检查内容。':'無法讀取方案庫，請保留檔案並檢查內容。',
'所选方案已不存在。':'所選方案已不存在。',
'方案名称请输入 1 至 60 个字符。':'方案名稱請輸入 1 至 60 個字元。',
'此方案名称已存在，请使用其他名称。':'此方案名稱已存在，請使用其他名稱。',
})
