"""Reviewed wording for the desktop interface."""
EN={
'当前方案 · 游戏实测':'Current combination · Measured in game',
'已测试方案 · 游戏实测':'Tested combination · Measured in game',
'候选方案 · 预测颜色':'Candidate · Predicted colors',
'正在定位此方案':'Positioning this combination',
'实测达标':'Measured within target',
'教程':'How to use','使用教程':'How to use Color Studio',
'支持作者':'Support the creator','♥  支持作者':'♥  Support',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'Supporting the creator is entirely optional. All features are available whether or not you donate.',
'选择您偏好的平台支持后续开发，感谢您的支持。':'Select a platform to support future development. Thank you.',
'爱发电':'Afdian','关闭':'Close','提交问题 / Issues':'Report an issue',
'1. 设置游戏窗口':'1. Set the game resolution',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'In the game, open Graphics → Display settings → Windowed mode → Resolution, and choose 1280 × 960.',
'2. 选择游戏窗口':'2. Select the game window',
'在本工具左上角选择正在运行游戏的窗口；只有一个游戏窗口时也可以使用自动检测。':'Select the game window at the top left of this tool. Auto-detect also works when only one game window is open.',
'3. 设置目标颜色':'3. Choose the target colors',
'设置需要固定的颜色，并启用对应染色区域。可输入 HEX 色码、点击选色，或使用屏幕吸管。':'Set the target colors and enable their dye regions. Enter HEX codes, choose a color, or use the eyedropper.',
'4. 选择匹配模式':'4. Choose a matching mode',
'5. 启动后再进入染色':'5. Start the tool, then open dyeing',
'按 F8 或点击开始。待浮窗出现后，再手动打开游戏内染色倒计时界面；识别成功后程序自动开始。':'Press F8 or click Start. Once the overlay appears, manually open the timed dye screen in the game. The tool starts automatically after recognizing it.',
'6. 自动操作期间':'6. While the tool is running',
'请尽量不要操作鼠标，保持游戏在前台，不要移动或缩放游戏窗口。按 F9 可随时停止；是否使用染色结果，请在游戏内手动确认。':'Avoid moving the mouse. Keep the game in the foreground and leave its window position and size unchanged. Press F9 to stop at any time; application must be confirmed manually in the game.',
'关于等待与候选方案':'Timing and alternative combinations',
'Tips 1 · 匹配方式':'Tip 1 · Matching modes',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'Exact HEX requires an identical code. Similar uses the configured Delta E tolerance; try 10 to start.',
'为每个区域选择精准或相似模式。':'Choose Exact or Similar for each region.',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。方案综合考虑各区域色差和落点附近的颜色变化，优先选择稳定、均衡的结果；整体质量相同时优先精准命中。':'Exact mode requires identical HEX codes; Similar mode uses the configured tolerance. Combinations are compared by color differences across all regions and nearby color variation, favoring stable, balanced results. Exact hits take priority when overall quality is equal.',
'本轮可执行方案均有区域偏离目标色系，以下按综合色差与落点稳定性排序。':'Every available executable combination has at least one region outside its target color family. Combinations are ranked by overall color difference and landing stability.',
'存在色系偏离':'Color family mismatch',
'部分区域与目标色系不符。':'Some regions do not match their target color families.',
'Tips 2 · 等待与候选':'Tip 2 · Waiting and alternatives',
'单区域会跳过整板拼接，使用平移和少量缩放直接寻色。精准模式从识别画板起约 60 秒内优先寻找精确 HEX，未命中时尝试定位本轮最佳实测妥协结果；收尾可能略多几秒。精准或相似目标连续两帧达标后立即停下，剩余时间可手动调整。多区域先拼图再寻色，浮窗会显示进度及候选方案。':'Single-region search skips full-board stitching and explores with translation and limited zoom. Exact mode prioritizes an identical HEX for about 60 seconds after board detection, then attempts to position the best measured compromise if no exact match is found; finalization may take a few extra seconds. The tool stops as soon as two consecutive readings meet the Exact or Similar target, leaving time for manual adjustment. With multiple regions enabled, it stitches the board before searching; the overlay shows progress and candidate combinations.',
'结果与问题反馈':'Results and feedback',
'自动染色并非完美，最终色差可能较大。如结果未达到预期，可重新开始一局。遇到问题请到 GitHub 提交 Issue，并附上本次日志。':'Automatic dyeing is not perfect, and the final color difference may be large. If the result is unsatisfactory, the round may be repeated. Report problems on GitHub with the session log.',
'就绪 · 请先选择游戏窗口和目标颜色':'Ready · Select the game window and target colors',
'拖动标题可移动浮窗':'Drag this header to move','不透明度':'Opacity','收起':'Collapse','展开':'Expand','停止 F9':'Stop F9',
'等待手动进入染色倒计时；F9 可停止。':'Open the timed dye screen manually. F9 stops.',
'识别与缩放':'Detecting and zooming','采集颜色板':'Capturing the board','对齐采集画面':'Aligning captured frames',
'测量色板周期':'Measuring board repetition','拼接全局颜色板':'Building the full board','保存颜色板':'Saving the board',
'检查拼图质量':'Checking board quality','搜索目标颜色':'Searching for target colors','计算旋转与缩放':'Calculating rotation and zoom',
'准备候选方案':'Preparing combinations','移动到目标位置':'Moving to the target','复核游戏色码':'Verifying game colors',
'正在按目标计算，请稍候。':'Calculating the color combinations. Please wait.',
'步骤 ':'Step ','已用 ':'Elapsed ',' 秒':' s','游戏剩余 ':'Game time left: ','本阶段 ':'This stage: ',
'区域 ':'Region ','预测 ':'Predicted ','实测 ':'Measured ','最大实测色差':'Maximum measured difference',
'自动方案实测色码':'Automatic result · game HEX',
'已停止，请查看游戏当前颜色。':'Stopped. Review the current colors in the game.',
'正在采集本局颜色板。':'Capturing this round’s color board.',
'等待用户手动进入倒计时染色界面':'Waiting for the timed dye screen to be opened.',
'候选选择已结束。':'Combination selection has ended.',
'全部目标达标，请在游戏内手动确认是否套用。':'All targets met. Confirm the final dye in the game.',
'正在定位所选方案':'Positioning the selected combination',
'根据图像实测位移校正；F9随时停止。':'Correcting the position using measured movement. F9 stops.',
'游戏色码已复核':'Game colors verified',
'图像处理中，鼠标暂时不动是正常现象。':'Images are being processed. The mouse stays still during this stage.',
'当前结果已达到所设目标，请在游戏内手动确认。':'The current result meets the configured targets. Confirm application manually in the game.',
'当前结果未达到全部目标；请先查看妥协方案，再在游戏内手动确认是否套用。':'Not all targets were met. Review the compromise result before deciding.',
'未找到满足所设目标的组合，正在定位最接近的妥协方案。':'No combination met the configured criteria. Positioning the closest compromise.',
'未精准匹配 · 妥协方案':'Not an exact match · Compromise',
'未命中目标 · 妥协方案':'Target not reached · Compromise',
'未找到满足目标的颜色；下方显示本轮已实测确认的妥协结果。这是寻色未命中后的正常结束状态，并非程序故障。请查看色差，并在游戏内手动确认是否采用。':'No color met the configured target. The result below is a measured compromise from this search. This is the normal outcome when no match is found, not a tool failure. Review the color difference and decide in the game whether to apply it.',
'未找到满足目标的颜色。此前最佳实测结果未能恢复；下方显示当前已复核的妥协结果，请以游戏内当前颜色为准。':'No color met the configured target. The previously measured best could not be restored; the compromise below shows the current verified result. Refer to the colors currently shown in the game.',
'妥协方案（未达目标） · 本次结果':'Compromise (target not reached) · Final result',
' · 最大色差 ΔE ':' · Maximum difference ΔE ',
' · 色差越小越接近目标':' · Lower is closer to the target',
'精准匹配':'Exact match',
'本轮搜索没有可测量的落点；无法生成自动或妥协方案。':'No measurable position was found. No automatic or compromise combination is available.',
'六位色码必须完全一致':'The six-digit HEX code must match exactly',
'目标色差 ΔE ≤ ':'Target color difference ΔE ≤ ',
' · 数值越小越接近目标':' · Lower values are closer to the target',
'正在采集本局颜色板':'Capturing this round’s color board',
'精准命中 ':'Exact HEX hits ',
'未找到游戏窗口。请启动游戏，或手动选择窗口。':'Game window not found. Start the game, or select its window manually.',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'The countdown could not be read reliably. No zoom or scan was started, but this dye was consumed. Check OCR before trying again.',
'正在复核倒计时识别':'Rechecking the countdown reading',
'正在寻色 · 游戏剩余 ':'Searching · game time left: ',
'正在恢复最佳颜色 · 游戏剩余 ':'Restoring the best colors · game time left: ',
'当前颜色  ':'Current color  ','最佳结果  ':'Best result  ',
'本次结果':'Current result','最佳组合':'Best combination',
'最大色差 ΔE ':'Maximum difference ΔE ',' / 平均 ':' / mean ',
' · 色差越小越接近目标':' · lower is closer to the target',
' 秒':' s',
}
TW={
'当前方案 · 游戏实测':'目前方案 · 遊戲實測',
'已测试方案 · 游戏实测':'已測試方案 · 遊戲實測',
'候选方案 · 预测颜色':'候選方案 · 預測顏色',
'正在定位此方案':'正在定位此方案',
'实测达标':'實測達標',
'等待用户手动进入倒计时染色界面':'等待您手動進入限時染色畫面。',
'Tips 1 · 匹配方式':'提示 1・比對模式','Tips 2 · 等待与候选':'提示 2・等待與候選',
'单区域会跳过整板拼接，使用平移和少量缩放直接寻色。精准模式从识别画板起约 60 秒内优先寻找精确 HEX，未命中时尝试定位本轮最佳实测妥协结果；收尾可能略多几秒。精准或相似目标连续两帧达标后立即停下，剩余时间可手动调整。多区域先拼图再寻色，浮窗会显示进度及候选方案。':'單區域會略過整板拼接，使用平移與少量縮放直接尋色。精準模式從辨識色板起約 60 秒內優先尋找精確 HEX，未命中時嘗試定位本局最佳實測折衷結果；收尾可能稍多幾秒。精準或相似目標連續兩幀達標後立即停止，剩餘時間可手動調整。多區域先拼圖再尋色，浮窗會顯示進度與候選方案。',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'精準 HEX 必須完全一致；相似模式依設定的 ΔE 容差搜尋，建議先從 10 開始。',
'为每个区域选择精准或相似模式。':'為每個區域選擇精準或相似模式。',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。方案综合考虑各区域色差和落点附近的颜色变化，优先选择稳定、均衡的结果；整体质量相同时优先精准命中。':'精準模式要求 HEX 完全一致；相似模式使用設定的色差範圍。方案綜合考量各區域色差與落點附近的顏色變化，優先選擇穩定、均衡的結果；整體品質相同時優先精準命中。',
'本轮可执行方案均有区域偏离目标色系，以下按综合色差与落点稳定性排序。':'本輪可執行方案皆有區域偏離目標色系，以下依綜合色差與落點穩定性排序。',
'存在色系偏离':'色系偏離',
'部分区域与目标色系不符。':'部分區域與目標色系不符。',
'六位色码必须完全一致':'六位色碼必須完全一致',
'目标色差 ΔE ≤ ':'目標色差 ΔE ≤ ',
' · 数值越小越接近目标':' · 數值越小越接近目標',
'正在采集本局颜色板':'正在採集本局顏色板',
'精准命中 ':'精準命中 ',
'未命中目标 · 妥协方案':'未命中目標・折衷方案',
'未找到满足目标的颜色；下方显示本轮已实测确认的妥协结果。这是寻色未命中后的正常结束状态，并非程序故障。请查看色差，并在游戏内手动确认是否采用。':'未找到符合目標的顏色；下方顯示本局已實測確認的折衷結果。這是未命中目標時的正常結束狀態，並非工具故障。請查看色差，並在遊戲內手動確認是否採用。',
'未找到满足目标的颜色。此前最佳实测结果未能恢复；下方显示当前已复核的妥协结果，请以游戏内当前颜色为准。':'未找到符合目標的顏色。先前最佳實測結果未能恢復；下方顯示目前已複核的折衷結果，請以遊戲內目前顏色為準。',
'妥协方案（未达目标） · 本次结果':'折衷方案（未達目標）・本次結果',
' · 最大色差 ΔE ':'・最大色差 ΔE ',
' · 色差越小越接近目标':'・色差越小越接近目標',
'教程':'使用教學','使用教程':'使用教學',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'贊助完全自願，無論是否贊助，都能正常使用本工具的所有功能。',
'选择您偏好的平台支持后续开发，感谢您的支持。':'如需支持後續開發，請選擇適合的平台。感謝您的支持。',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'在遊戲中依序開啟【圖形】→【畫面設定】→【視窗模式】→【解析度】，設為 1280 × 960。',
'提交问题 / Issues':'回報問題 / Issues',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'倒數計時無法可靠辨識，未開始縮放或掃描；本次染劑已消耗，請先檢查 OCR 再重新執行。',
}
