"""Reviewed wording for the desktop interface."""
EN={
'当前方案 · 游戏实测':'Current combination · Measured in game',
'已测试方案 · 游戏实测':'Tested combination · Measured in game',
'候选方案 · 预测颜色':'Candidate · Predicted colors',
'正在定位此方案':'Positioning this combination',
'实测达标':'Measured within target',
'教程':'How to use','使用教程':'How to use Color Studio',
'支持作者':'Support the creator','♥  支持作者':'♥  Support',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'Supporting the creator is entirely optional. All features are available whether or not you donate.',
'选择您偏好的平台支持后续开发，感谢您的支持。':'Select a platform to support future development. Thank you.',
'爱发电':'Afdian','关闭':'Close','提交问题 / Issues':'Report an issue',
'1. 设置游戏窗口':'1. Set the game resolution',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'In the game, open Graphics → Display settings → Windowed mode → Resolution, and choose 1280 × 960.',
'2. 选择游戏窗口':'2. Select the game window',
'在本工具左上角选择正在运行游戏的窗口；只有一个游戏窗口时也可以使用自动检测。':'Select the game window at the top left of this tool. Auto-detect also works when only one game window is open.',
'3. 设置目标颜色':'3. Choose the target colors',
'设置需要固定的颜色，并启用对应染色区域。可输入 HEX 色码、点击选色，或使用屏幕吸管。':'Set the target colors and enable their dye regions. Enter HEX codes, choose a color, or use the eyedropper.',
'4. 选择匹配模式':'4. Choose a matching mode',
'5. 启动后再进入染色':'5. Start the tool, then open dyeing',
'按 F8 或点击开始。待浮窗出现后，再手动打开游戏内染色倒计时界面；识别成功后程序自动开始。':'Press F8 or click Start. Once the overlay appears, manually open the timed dye screen in the game. The tool starts automatically after recognizing it.',
'6. 自动操作期间':'6. While the tool is running',
'请尽量不要操作鼠标，保持游戏在前台，不要移动或缩放游戏窗口。按 F9 可随时停止；是否使用染色结果，请在游戏内手动确认。':'Avoid moving the mouse. Keep the game in the foreground and leave its window position and size unchanged. Press F9 to stop at any time; application must be confirmed manually in the game.',
'关于等待与候选方案':'Timing and alternative combinations',
'Tips 1 · 匹配方式':'Tip 1 · Matching modes',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'Exact HEX requires an identical code. Similar uses the configured Delta E tolerance; try 10 to start.',
'为每个区域选择精准或相似模式。':'Choose Exact or Similar for each region.',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。妥协方案优先保持各区域色系，再优先减小精准区域色差。':'Exact mode requires identical HEX codes; Similar mode uses the configured tolerance. Compromises prioritize preserving each region’s color family, then reducing differences in Exact regions.',
'本轮搜索未找到所有区域均保持目标色系的可执行组合，以下为偏色较少的妥协方案。':'This search found no executable combination that preserves every target color family. The listed compromises have the smallest family deviations found.',
'存在色系偏离':'Color family mismatch',
'部分区域与目标色系不符。':'Some regions do not match their target color families.',
'Tips 2 · 等待与候选':'Tip 2 · Waiting and alternatives',
'工具先拼接本局色板，再搜索并定位；浮窗会显示进度。想改选其他方案，请尽早点击候选卡。倒计时不足以安全移动和复核时，程序会保持当前方案。':'The tool stitches this round’s board before searching and positioning; the overlay shows progress. Click a candidate card promptly to choose another option. If there is not enough time to move and verify safely, the current option is kept.',
'结果与问题反馈':'Results and feedback',
'自动染色并非完美，最终色差可能较大。如结果未达到预期，可重新开始一局。遇到问题请到 GitHub 提交 Issue，并附上本次日志。':'Automatic dyeing is not perfect, and the final color difference may be large. If the result is unsatisfactory, the round may be repeated. Report problems on GitHub with the session log.',
'就绪 · 请先选择游戏窗口和目标颜色':'Ready · Select the game window and target colors',
'拖动标题可移动浮窗':'Drag this header to move','不透明度':'Opacity','收起':'Collapse','展开':'Expand','停止 F9':'Stop F9',
'等待手动进入染色倒计时；F9 可停止。':'Open the timed dye screen manually. F9 stops.',
'识别与缩放':'Detecting and zooming','采集颜色板':'Capturing the board','对齐采集画面':'Aligning captured frames',
'测量色板周期':'Measuring board repetition','拼接全局颜色板':'Building the full board','保存颜色板':'Saving the board',
'检查拼图质量':'Checking board quality','搜索目标颜色':'Searching for target colors','计算旋转与缩放':'Calculating rotation and zoom',
'准备候选方案':'Preparing combinations','移动到目标位置':'Moving to the target','复核游戏色码':'Verifying game colors',
'正在按目标计算，请稍候。':'Calculating the color combinations. Please wait.',
'步骤 ':'Step ','已用 ':'Elapsed ',' 秒':' s','游戏剩余 ':'Game time left: ','本阶段 ':'This stage: ',
'区域 ':'Region ','预测 ':'Predicted ','实测 ':'Measured ','最大实测色差':'Maximum measured difference',
'自动方案实测色码':'Automatic result · game HEX',
'已停止，请查看游戏当前颜色。':'Stopped. Review the current colors in the game.',
'正在采集本局颜色板。':'Capturing this round’s color board.',
'等待用户手动进入倒计时染色界面':'Waiting for the timed dye screen to be opened.',
'候选选择已结束。':'Combination selection has ended.',
'全部目标达标，请在游戏内手动确认是否套用。':'All targets met. Confirm the final dye in the game.',
'正在定位所选方案':'Positioning the selected combination',
'根据图像实测位移校正；F9随时停止。':'Correcting the position using measured movement. F9 stops.',
'游戏色码已复核':'Game colors verified',
'图像处理中，鼠标暂时不动是正常现象。':'Images are being processed. The mouse stays still during this stage.',
'当前结果已达到所设目标，请在游戏内手动确认。':'The current result meets the configured targets. Confirm application manually in the game.',
'当前结果未达到全部目标；请先查看妥协方案，再在游戏内手动确认是否套用。':'Not all targets were met. Review the compromise result before deciding.',
'未找到满足所设目标的组合，正在定位最接近的妥协方案。':'No combination met the configured criteria. Positioning the closest compromise.',
'未精准匹配 · 妥协方案':'Not an exact match · Compromise',
'精准匹配':'Exact match',
'本轮搜索没有可测量的落点；无法生成自动或妥协方案。':'No measurable position was found. No automatic or compromise combination is available.',
'六位色码必须完全一致':'The six-digit HEX code must match exactly',
'目标色差 ΔE ≤ ':'Target color difference ΔE ≤ ',
' · 数值越小越接近目标':' · Lower values are closer to the target',
'正在采集本局颜色板':'Capturing this round’s color board',
'精准命中 ':'Exact HEX hits ',
'未找到游戏窗口。请启动游戏，或手动选择窗口。':'Game window not found. Start the game, or select its window manually.',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'The countdown could not be read reliably. No zoom or scan was started, but this dye was consumed. Check OCR before trying again.',
'正在复核倒计时识别':'Rechecking the countdown reading',
'正在寻色 · 游戏剩余 ':'Searching · game time left: ',
'正在恢复最佳颜色 · 游戏剩余 ':'Restoring the best colors · game time left: ',
'当前颜色  ':'Current color  ','最佳结果  ':'Best result  ',
'本次结果':'Current result','最佳组合':'Best combination',
'最大色差 ΔE ':'Maximum difference ΔE ',' / 平均 ':' / mean ',
' · 色差越小越接近目标':' · lower is closer to the target',
' 秒':' s',
}
TW={
'当前方案 · 游戏实测':'目前方案 · 遊戲實測',
'已测试方案 · 游戏实测':'已測試方案 · 遊戲實測',
'候选方案 · 预测颜色':'候選方案 · 預測顏色',
'正在定位此方案':'正在定位此方案',
'实测达标':'實測達標',
'等待用户手动进入倒计时染色界面':'等待您手動進入限時染色畫面。',
'Tips 1 · 匹配方式':'提示 1・比對模式','Tips 2 · 等待与候选':'提示 2・等待與候選',
'精准 HEX 必须完全一致；相似模式按设定的 ΔE 容差搜索，建议从 10 开始。':'精準 HEX 必須完全一致；相似模式依設定的 ΔE 容差搜尋，建議先從 10 開始。',
'为每个区域选择精准或相似模式。':'為每個區域選擇精準或相似模式。',
'精准模式要求 HEX 完全一致；相似模式使用设定的色差范围。妥协方案优先保持各区域色系，再优先减小精准区域色差。':'精準模式要求 HEX 完全一致；相似模式使用設定的色差範圍。折衷方案優先維持各區域色系，再優先縮小精準區域的色差。',
'本轮搜索未找到所有区域均保持目标色系的可执行组合，以下为偏色较少的妥协方案。':'本輪搜尋未找到所有區域皆維持目標色系且可執行的組合，以下為色系偏差較小的折衷方案。',
'存在色系偏离':'色系偏離',
'部分区域与目标色系不符。':'部分區域與目標色系不符。',
'工具先拼接本局色板，再搜索并定位；浮窗会显示进度。想改选其他方案，请尽早点击候选卡。倒计时不足以安全移动和复核时，程序会保持当前方案。':'工具會先拼接本局色板，再搜尋並定位；浮窗會顯示進度。想改選其他方案，請儘早點選候選卡。若倒數時間不足以安全移動及複核，程式會保留目前方案。',
'六位色码必须完全一致':'六位色碼必須完全一致',
'目标色差 ΔE ≤ ':'目標色差 ΔE ≤ ',
' · 数值越小越接近目标':' · 數值越小越接近目標',
'正在采集本局颜色板':'正在採集本局顏色板',
'精准命中 ':'精準命中 ',
'教程':'使用教學','使用教程':'使用教學',
'赞助完全自愿，不论是否赞助，都可以正常使用本工具的全部功能。':'贊助完全自願，無論是否贊助，都能正常使用本工具的所有功能。',
'选择您偏好的平台支持后续开发，感谢您的支持。':'如需支持後續開發，請選擇適合的平台。感謝您的支持。',
'在游戏中依次打开【图形】→【畫面設定】→【視窗模式】→【解析度】，设为 1280 × 960。':'在遊戲中依序開啟【圖形】→【畫面設定】→【視窗模式】→【解析度】，設為 1280 × 960。',
'提交问题 / Issues':'回報問題 / Issues',
'倒计时无法可靠识别，未开始缩放或扫描；本次入口已消耗染色剂，请检查 OCR 后再运行。':'倒數計時無法可靠辨識，未開始縮放或掃描；本次染劑已消耗，請先檢查 OCR 再重新執行。',
}
